### ISSUE TITLE
Parameter sharing

### ISSUE THREAD

**Issue by an-ju** [an-ju/projectscope#16]
Right now gems do not share parameters, meaning that each gem has its own set of parameter and the user has to input the same parameter multiple times. Parameters should be controlled in a single "hub" and shared among gems.

It may need gems to have an extra API that returns a list parameters it requires.

**Comment by stevenwuyinze** [comment]
We need more information here. Do you mean if gem A needs param1, gem B also needs param2, we only need to make user input param1 once? What is an example of this?

Nevertheless, I don't think it's even necessary to do so. Most params won't overlap. It's also better to keep them separate from implementation point of view.

**Comment by stevenwuyinze** [comment]
It's better to maintain separate record also because I want to verify the correctness and completeness of params needed every time a user adds in another metric. Consider the following workflows:

1. User wants to add a new metric to desiganted project-> System shows which params it needs from the project -> User puts in needed params -> System do the check.

2. User adds in every params he thinks what are the needed params (but forgets to put one) -> System saves every thing but cannot check completeness and correctness -> System halts when it tries to update but finds params missing.

**Comment by an-ju** [comment]
Sorry I forgot to read you comments.

I believe our talk on this issue is after these comments. So is it clearer to you now what I want to do?

The reason I'd like to share parameters is that it is very likely a single data source (for example, GitHub) has multiple gems. All these gems actually need the same set of parameters. So it is more clean to manage all parameters in a single place.

As we've discussed, I believe it requires a change of database. Under config, we should add another one called parameter, which contains all encrypted key-value pairs.

**Comment by an-ju** [comment]
Merged in PR #40 . It only works with new gems (gems that have credentials API).
